### ISSUE TITLE
Ensure sensitive information is not exposed through error messages

### ISSUE THREAD

**Issue by krishishah** [moov-io/iso8583#103]
I've noticed with debugging some code that this library sometimes exposes sensitive information via error messages. An example of this is if `strconv.Atoi(...)` returns an error as part of `Numeric.Unpack(...)`. 

The library wraps around the error and adds additional context. However, `strconv.Atoi(...)` returns the value of the string that it could not convert to an int. Sensitive information could live inside of this field and may be accidentally exposed in logs.

We should ensure that errors from third party dependencies are handled such that this information would not be propagated. Same applies to errors generated directly by the library.

**Comment by alovak** [comment]
@krishishah what are your ideas on how we can make it work?

**Comment by alovak** [comment]
@krishishah what do you think about idea of adding `Mask` into the field Spec described in [#102](https://github.com/moov-io/iso8583/issues/102#issuecomment-883433580)?

**Comment by vtolstov** [comment]
I'm prefer to have generic func that get field value and able to modify it. So for PAN i want to write stars in some positions, but other people wants to encrypt PAN and HEX encode it.

**Comment by krishishah** [comment]
I'm not sure how applicable #102 is to this issue. I see `describe` as a tool whose job it is to display field values and the data elements they correspond to. A `mask` flag seems more appropriate there given its job.

Error messages via `Pack` and `Unpack` on the other hand, will be returned in a production environment and likely logged by users of this library on receipt of one. 

I personally don't see a strong enough use case to display the contents of a field which has errored out. Failing tests would provide enough context into the input which caused the failure. The error messages returned by this library already return which fields and subfields have errored out. IMO that provides sufficient context into what has gone wrong without the risk of exposing such details.

> I'm prefer to have generic func that get field value and able to modify it. So for PAN i want to write stars in some positions, but other people wants to encrypt PAN and HEX encode it.

I don't see how to do this if a 3rd party lib / std lib is the one generating the error - it's out of our control. 

Our best bet IMO is to write unit tests to assert on the concrete string returned by an error within this library as done in `field/composite_test.go` (this is incidentally how I discovered that `strconv.Atoi` returns the contents of the input in its error message). We would also need to test all of our error branches to ensure that sensitive data is not leaked and plug those gaps where appropriate. Implementing masking behaviour would require this to be done anyways to ensure that masking works as desired.

**Comment by cheukwing** [comment]
From a look over the code base, most (if not all) of the error messages returned do not embed any field data (and hence, no sensitive information).
However, it does wrap the errors from standard and third party libraries, which do (or could in the future) embed field data in the error message.
As Krishi mentioned, the error messages returned by the library already contain enough information about the sub/field which has errored, so we can simply stop wrapping external library errors to solve this issue.

**Comment by alovak** [comment]
I agree we should remove sensitive information from errors when we encode/decode field values. I would keep error wrapping in places where it's safe.

Also, as an idea, we can introduce an error type like `SafeError` that will allow the end user to get an underlying error through a method like `UnsafeUnwrap() error`.

**Comment by cheukwing** [comment]
Good idea with `SafeError`! I will start working on this
