### ISSUE TITLE
Support reading / writing a nibble for network headers. 

### ISSUE THREAD

**Issue by wadearnold** [moov-io/iso8583#104]
A nibble is used in many of the network management message headers. We will need to be able to read and write a header that supports a nibble. 

In computers and digital technology, a nibble (pronounced NIHB-uhl; sometimes spelled nybble) is four binary digits or half of an eight-bit byte. A nibble can be conveniently represented by one hexadecimal digit. In communications, a nibble is sometimes referred to as a "quadbit." or one of 16 possible four-bit combinations

Existing ideas. 

https://github.com/LethalEthan/Go-Nibble
https://github.com/bake/nibble
https://github.com/wiggin77/nibs

**Comment by alovak** [comment]
I'm not sure, but it seems we already have it here:

https://github.com/moov-io/iso8583/blob/master/network/bcd_2bytes_test.go#L21

BCD represents encoding where 1 digit is 4 bits (nibble). We can read the network header with 4 BCD digits that are represented by 2 bytes.

**Comment by wadearnold** [comment]
I know that we do it. I was just thinking we could make a function for it. I will close this for now.
