### ISSUE TITLE
Generate STAN(System Trance Audit Number) for Field 11 

### ISSUE THREAD

**Issue by wadearnold** [moov-io/iso8583#107]
Create an interface to generate a STAND that is used as a trace number between messages sent and received. The implementation should be an interface with a concrete thread-safe in-memory concrete implementation. The returned value will be placed into Field11 of an ISO8583 message. 

```go 
// STANGenerator defines the behavior needed to provide sequence numbers for newly created iso messages.
// It must provide sequence numbers between 1 and 999999, as per the ISO standard.
// The value is put into field 11. 
type STANGenerator interface {
    // Returns the next STAN for a trace number
    NextSTAN() int
    // returns the last STAN that was generated 
    LastStan() int 
}
```

**Comment by alovak** [comment]
We then also need RRN generator :)

**Comment by wadearnold** [comment]
I agree on the RRN generator. Both need an in-memory implementation. I assume that we will want one that persists in a restart at some point.

**Comment by adamdecaf** [comment]
If you want to use file locking I'd checkout https://github.com/gofrs/flock which can help you persist the STAN across restarts.

Btw, is this called "trace" or "trance"? STAN or STAND?

**Comment by alovak** [comment]
We will add generation on STAN and RRN into client/server package. Not sure they should be in this package. Closing for now.
