### ISSUE TITLE
Add fuzzing for parser

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/iso8583#11]
We need to add fuzzing to this project. Fuzzing helps prove out panics and errors by trying a wide spectrum of input to make the project safer to run in production. 

Setup a test to parse input: https://github.com/moov-io/iso8583/blob/master/parser.go

We have other fuzzing examples here: https://github.com/moov-io/ach/tree/master/test/fuzz-reader which uses https://github.com/dvyukov/go-fuzz

**Comment by mfdeveloper508** [comment]
https://github.com/moov-io/iso8583/pull/28
