### ISSUE TITLE
Network writing of messages is not concurrent safe using existing API

### ISSUE THREAD

**Issue by krishishah** [moov-io/iso8583#117]
Moov's documentation suggests that users write messages to the network as such:

```
header := network.NewBCD2BytesHeader()
packed, err := message.Pack()
if err != nil {
	// handle error
}
header.SetLength(len(packed))
_, err = header.WriteTo(conn)
if err != nil {
	// handle error
}
n, err := conn.Write(packed)
if err != nil {
	// handle error
}
```

`net.Conn` allows for concurrent safe writes so long as all bytes (both header and body) are written to the network in a single call.

The usage pattern above would not allow for multiple concurrent writes to occur using the same connection as the header and packed message are written across 2 calls to `conn.Write(...)`.

In addition, the experience of making two separate calls is quite fiddly with lots of error handling interleaved. 

I suggest that we improve the API of this library to allow for writes of both the packed message and the header to take place over a single call to the library (and to `conn.Write` for concurrent write safety).

**Comment by krishishah** [comment]
Thanks @alovak ! 

Am I right in thinking you actually wrap the connection around in something like a `bufio.Writer(conn)`?  If so it could also be done like this without needing locks:

```
	msg, err := message.Pack()
	if err != nil {
            // handle error
	}
	
	header := network.NewBinary2BytesHeader()
	header.SetLength(len(msg))
	writer := bufio.NewWriterSize(conn, headerLen+header.Length())
	if _, err := header.WriteTo(writer); err != nil {
		// handle err
	}
	if _, err := writer.Write(msg); err != nil {
		// handle err
	}
	if err := writer.Flush(); err != nil {
		// handle err
	}
	return nil
```

You wouldn't need locks since your `bufio.Writer` won't be shared between threads here and `net.Conn` will provide you with concurrent write safety out of the box when you call `writer.Flush()`

**Comment by alovak** [comment]
Yeah, you are right. Reading the `net.Conn` I see: 

> Multiple goroutines may invoke methods on a Conn simultaneously. 

and I also think that there is no real reason for us to share `bufio.Writer`
