### ISSUE TITLE
differentiated header

### ISSUE THREAD

**Issue by Juniornewxt** [moov-io/iso8583#119]
Hello friends,
I have a problem now, I got a specification, where I need to put the following information in the header:
Message size in binary.
and TPDU.
Example:
01 63 60 00 06 00 00
Being:
01 63 = message size in binary.
60 00 06 00 00 = TPDU.

You have no idea how to make this work, can you help me?

**Comment by alovak** [comment]
What's in TPDU? Is it fixed and always `60 00 06 00 00`?

We have a set of network headers that you may look at and create your own. Please, check this header: https://github.com/moov-io/iso8583/blob/master/network/binary_2bytes.go as it reads 2 bytes from the reader and uses them to calculate the length.

You can read 7 bytes, but keep the logic of size calculation using the first 2 bytes. For your case, I created a header that reads 7 bytes from the network and uses the first 2 bytes as length: https://gist.github.com/alovak/2ebd064c088e3496db0cd8d073ebdd4b Please note, it works only when you read the message and may need some testing :)

When you have a header, you can read it from the connection and then read the message:

```
header := NewBinary7BytesHeader()

// lock connection so only you can read from it
_, err := header.ReadFrom(conn)
// handle err

// create slice for your message
packed := make([]byte, header.Length())
_, err := conn.Read(packed)
// handle err
// unlock connection so other can read from it

// now you can unpack the message
err = message.Unpack(packed)
// handle err

```

**Comment by Juniornewxt** [comment]
@alovak 
Yes, tpdu will be fixed.
The structure of the message is:
header/tpdu/iso-message

**Comment by alovak** [comment]
Then you can use header from the [gist](https://gist.github.com/alovak/2ebd064c088e3496db0cd8d073ebdd4b) + example how to read header and message.

**Comment by Juniornewxt** [comment]
I did not understand.
The iso-message I will generate and send to the system.
But my message needs to have the header with size+tpdu, before the iso message.

**Comment by Juniornewxt** [comment]
here's an example, as a part of the message I'm supposed to send.
note that before the iso message there is 01 63 60 00 06 00 00

01 63 60 00 06 00 00 30 32 30 30 33 32 33 38 36 34 30 31 32 38 45 ...

**Comment by alovak** [comment]
Ok. My gist is only to read the header. Not to write. If you want to write [header][tpdu][message], I see following steps:

1. create and pack message
1. create and write header with length(packed)
2. create tpdu
3. combine all data
3. write data into connection

Here is how it may be done (not tested, typing right here):

```go

// 1
msg := iso8583.NewMessage(...)
// ...
packed := msg.Pack()

// 2
header := network.NewBinary2BytesHeader()
header.SetLength(len(packed))

// 3
tpdu := []byte(...)

//4 - combine all we have into one buf

var buf bytes.Buffer

header.WriteTo(&buf)
n, err = buf.Write(tpdu)
n, err = buf.Write(packed)


// 5 - now you can write everything into connection
conn.Write(buf.Bytes()) 

```

**Comment by Juniornewxt** [comment]
Fantastic, I was able to read the send header, just not being able to read the header on the return.
No problem, I'm still studying here.
Thank you very much.
