### ISSUE TITLE
Error undefined: encoding.Hex latest version

### ISSUE THREAD

**Issue by Juniornewxt** [moov-io/iso8583#140]
Friends, since I updated the moov package, I can't compile getting the error
:undefined: encoding.Hex

If I go back to the github.com/moov-io/iso8583 v0.4.11 version
I don't have this problem, has anything changed?

**Comment by cahyoarifandiyartoo** [comment]
try with encoding.BytesToASCIIHex with prefixer prefix.Hex.Fixed
