### ISSUE TITLE
Documentation, Typed vs unTyped is confusing

### ISSUE THREAD

**Issue by wadearnold** [moov-io/iso8583#142]
Combine the typed and untyped sections together. There should be an intro for why you would want to use Typed vs Untyped spec's in this library.

**Comment by alovak** [comment]
Not sure I understand :) Maybe you can give me an example?

**Comment by wadearnold** [comment]
I apologize. I had two tabs open and read the `message.Marshal(data)` instead of the updated readme. Please ignore.

**Comment by alovak** [comment]
I'll close the issue then! Thanks for reading the docs and noticing the issues! :D
