### ISSUE TITLE
Expiratin date in track1 and track2 allows only YYMM

### ISSUE THREAD

**Issue by Scratch-net** [moov-io/iso8583#154]
It is hardcoded in Track1 and Track2 that the expiration date format is YYMM while it can be the other way around.
Could this format be made configurable?

**Comment by adamdecaf** [comment]
@Scratch-net I don't see validation for expiration date to require that. I do see it specified as an alpha string in the example. Do you need help with this? 

 https://github.com/moov-io/iso8583/blob/master/specs/spec87ascii.go#L106

**Comment by Scratch-net** [comment]
Actually, it was my mistake, sorry. When calculating CVC you can choose MMYY or YYMM but in the track itself it's mandatory YYMM, I didn't know that. 
Thanks for the great library!
