### ISSUE TITLE
package api problems

### ISSUE THREAD

**Issue by vtolstov** [moov-io/iso8583#170]
I'm try to rewrite old way4 iso8583 parser.
Before latest many changes i can Unmarshal data to own message (contains all fields with their types) and after that i can create new message and assign some fields to it from incoming message.
Now i see only two methods - GetString and GetBytes, in this case for numeric fields i need to convert from string to int and this is really expensive.
Why i cant get native field data type?

Also SetMTI method accept string, but package contains predefined MTI types with custom type, so SetMTI needs additional casting to string type....

**Comment by alovak** [comment]
@vtolstov Not sure I understand this part:
> Now i see only two methods - GetString and GetBytes, in this case for numeric fields i need to convert from string to int and this is really expensive.

We have `message.Unmarshal` ([test](https://github.com/moov-io/iso8583/blob/master/message_test.go#L1367)) and `message.Marshal` ([test](https://github.com/moov-io/iso8583/blob/master/message_test.go#L1281))

I'm not sure that we will keep MTI type. Internally, we do not use them. But I see it's confusing.

**Comment by vtolstov** [comment]
Yeah thanks, i'm miss that after Unpack I need to call Unmarshal to my struct.
