### ISSUE TITLE
Support Composite field with bitmap

### ISSUE THREAD

**Issue by alovak** [moov-io/iso8583#172]
How to pack/unpack fields with their own bitmap and subelements?

**Comment by tloriato** [comment]
I'm not sure how to solve this, but if we could attribute an ISO8583 spec as an "encoding" type maybe...? Looks like a big change?

**Comment by FacundoMora** [comment]
Hi everyone!
About this issue, is there any of you working on a solution?

**Comment by SahibYar** [comment]
based on this comment https://github.com/moov-io/iso8583/issues/177#issuecomment-1613632040

is this issue still open ?

**Comment by alovak** [comment]
Support for bitmaps in composite fields was added in https://github.com/moov-io/iso8583/pull/229
