### ISSUE TITLE
VISA specification example

### ISSUE THREAD

**Issue by Juniornewxt** [moov-io/iso8583#175]
Hello friends, do any of you have an example of a basic specification of Visa?

Example:
Fields: map[int]field.Field{
			0: field.NewString(&field.Spec{
				Length:      4,
				Description: "MTI",
				Enc:         encoding.BCD,
				Pref:        prefix.BCD.Fixed,
			}),
			1: field.NewBitmap(&field.Spec{
				Description: "Bitmap",
				Enc:         encoding.ASCII,
				Pref:        prefix.Binary.Fixed,
			}),
			2: field.NewString(&field.Spec{
				Length:      19,
				Description: "Primary Account Number",
				Enc:         encoding.BCD,
				Pref:        prefix.BCD.LL,
			}),
			3: field.NewNumeric(&field.Spec{
				Length:      6,
				Description: "Proc code",
				Enc:         encoding.BCD,
				Pref:        prefix.BCD.Fixed,
				Pad:         padding.Left('0'),
			}),
			4: field.NewNumeric(&field.Spec{
				Length:      12,
				Description: "Amount",
				Enc:         encoding.BCD,
				Pref:        prefix.BCD.Fixed,
				Pad:         padding.Left('0'), .....

**Comment by vtolstov** [comment]
what server will be used for iso8583 traffic? i have old visa docs, but spec depends on server (way4/tieto/altavista etc)

**Comment by wadearnold** [comment]
We are working with the card brands to get some of these specifications open sourced. For now, you will need to reference the Visa online portal and this is included in the "BASE I Processing Specifications".

**Comment by adamdecaf** [comment]
We use https://github.com/moov-io/iso8583-connection to create and manage our 8583 connections in production.

**Comment by Juniornewxt** [comment]
> what server will be used for iso8583 traffic? i have old visa docs, but spec depends on server (way4/tieto/altavista etc)

Thanks friend, I don't know if I understand the question, but the message will travel via tcpip, I have the documentation, but it seems to me that VISA uses bcd, and I don't know if I really understood the specification, so I asked if they had any examples.
I have already set up other programs with specification of Brazilian flags, but VISA seems a little different to me.

**Comment by Juniornewxt** [comment]
> We are working with the card brands to get some of these specifications open sourced. For now, you will need to reference the Visa online portal and this is included in the "BASE I Processing Specifications".

Thanks friend, yes I have the documentation but I think I didn't understand correctly the use of bcd in most BIT VISA

**Comment by Juniornewxt** [comment]
> We use https://github.com/moov-io/iso8583-connection to create and manage our 8583 connections in production.

Thanks friend, I didn't understand that you are referring me, sorry.
My programs today are just to simulate transactions in a test environment, to automate tests, to simulate POS or the message coming from "Brand" :).
