### ISSUE TITLE
qr generate

### ISSUE THREAD

**Issue by vtolstov** [moov-io/iso8583#176]
mostly offtopic question - but how generate qr for visa payment?
I have bin/pan and other data and visa spec, but don't understand how generate qr in go.
Golang qr generators get []byte or string and output qr. In case of qr for payment in visa - in what format data must be converted before encode it to QR ?

**Comment by adamdecaf** [comment]
@vtolstov To clarify, what do you mean by QR?

**Comment by vtolstov** [comment]
so i'm found solution
https://pkg.go.dev/go.mercari.io/go-emv-code/mpm
https://pkg.go.dev/giautm.dev/emvqr
https://github.com/dongri/emv-qrcode

**Comment by adamdecaf** [comment]
Cool! Let us know if you need help with the iso8583 library.
