### ISSUE TITLE
Set empty value (zero value) for missing fields when unmashaling message into data struct

### ISSUE THREAD

**Issue by alovak** [moov-io/iso8583#195]
# The problem

Let's imagine we have a following type:

```go
type NetworkManagementRequest struct {
	MTI                  *field.String `index:"0"`
	TransmissionDateTime *field.String `index:"7"`
	STAN                 *field.String `index:"11"`
	InformationCode      *field.String `index:"70"`
}
```

When we unmarshal message fields into the data struct before we access the field value, we should check if field is not nil:

```go
data := &NetworkManagementRequest{}
err := message.Unmarshal(data)
// handle error

// it's not always safe to access field value like this:
fmt.Printf("MTI: %s\n", data.MTI.Value)

// if field is not set in the message, then the corresponding field in the data struct will be nil
fmt.Printf("InformationCode": %s\n", data.InformationCode.Value) // => will panic

// so, to avoid this
if data.InformationCode != nil {
	// do something with the value
	data.InformationCode.Value
}
```

# Proposal for the solution
We can add  a value for the field tag e.g., `addempty` (it's like the opposite of `omitempty` for `json` tag), which will set an empty/zero value to the field when we message.Unmarshal(data) and the field was not in the message.

Example:

```go
type NetworkManagementRequest struct {
	MTI                  *field.String `index:"0"`
	TransmissionDateTime *field.String `index:"7"`
	STAN                 *field.String `index:"11"`
	InformationCode      *field.String `index:"70,addempty"`
}
```

Please, feel free to propose a better name instead of `addempty`.

P.S. having a tag with the name `index` looks weird, I think it's time to introduce the `iso8583` tag and keep `index` as an alias for backward compatibility.

**Comment by adamdecaf** [comment]
`addempty` is a handy name for always populating `*field.T` values, so that makes sense to me. 

Is there a difference between adding this tag and guarding the accessor better? I understand this proposal would remove the possibility of nil panics on `.Value` access requests. Maybe both changes are needed?

We could guard the accessor methods better to avoid panics. See https://github.com/moov-io/iso8583/pull/196

**Comment by alovak** [comment]
I think guarding accessor is something we definitely should add! Because in many places, we access `.Value` (as it's more convenient because `String()` returns two values), we should add `addempty` too.

**Comment by alovak** [comment]
What if we add `Value()` method for nil receiver will return zero value? Then we don't need  to add `addempty`... we will just replace `posData.Field.Value` with `posData.Field.Value()`

**Comment by alovak** [comment]
Oh... except that I forgot we have a `Field` interface and we can't add `Value()` method as returning type is different for different fields (String, Numeric, Composite)

**Comment by adamdecaf** [comment]
We could add `GetValue() T` that safely returns `.Value` (or the zero value of that type).

**Comment by alovak** [comment]
So far, the work that @adamdecaf did in https://github.com/moov-io/iso8583/pull/196 is enough to solve most of the cases mentioned here.

We will have to check for `nil` only composite fields in cases like this:

```go
type AuthorizationRequest struct {
	MTI                  *field.String `index:"0"`
	TransmissionDateTime *field.String `index:"7"`
	STAN                 *field.String `index:"11"`
	AdditionalData *AdditionalData `index:"12"`
}

type AdditionalData struct {
	Type                  *field.String `index:"1"`
	Value                  *field.String `index:"1"`
}

// here we have to check that AdditionalData was set before accessing its values
if authRequest.AdditionalData != nil {

}
```

Keeping changes of the tag name and addition of `addempty` for the future
