### ISSUE TITLE
version1987.go:   Change Field 36:  Track 3 Data from n..104 to z..104

### ISSUE THREAD

**Issue by SharonAllsup** [moov-io/iso8583#21]
Should Track 3 Data be n..104 or z..104?

_Originally posted by @SharonAllsup in https://github.com/moov-io/iso8583/pull/20#r524606889_

**Comment by mfdeveloper508** [comment]
Field 36 is n..104
DE 36—TRACK-3 DATA (https://github.com/moov-io/iso8583/blob/master/docs/MDSSEC04.PDF)
