### ISSUE TITLE
MAC for message

### ISSUE THREAD

**Issue by Kamyab96** [moov-io/iso8583#253]
I need create Mac from message , but we dont have method for that ,
or i need create additional data with tag 45 , 34 or parse response .

is there any solution ?

**Comment by Kamyab96** [comment]
i need calculate MAC for message and send it in field 64 .
MAC is 8 last bytes of encrypted text by 3 DES - CBC algorithm .
for  Example : 

‫‪Plain‬‬ ‫‪data:‬‬ 
‫‪0800603804010881000116837299000022446695128200000209514005310100061999001200000000‬‬‫‪243139303030303239000702000430303030‬‬

‫‪Zero‬‬ ‫‪Padded‬‬ ‫‪data:‬‬
‫‪0800603804010881000116837299000022446695128200000209514005310100061999001200000000‬‬‫‪2431393030303032390007020004303030300000000000‬‬

After padding the data, the length of data bytes should be divisible by 8 

‫‪Key:‬‬ ‫‪1A1B1C1D1E1F2A2B2C2D2E2F3A3B3C3D‬‬

‫‪Encrypted‬‬ ‫‪data‬‬ ‫;‪(3DES-CBC‬‬ ‫‪IV=0):‬‬
c278835471ea1483b79c17fb48e2586207ce4359aeac001f69b0f4e64a3c8d7a3f5a3b09dd99f2f8eca460a4ce2f801994261cad2665b3fe23d628cf6063ad4e


MAC : 23d628cf6063ad4e

**Comment by alovak** [comment]
Hey, @Kamyab96 I'm not sure about adding MAC calculation to the iso8583 package yet as there are not many examples currently. I also can't give you the correct answer, maybe code samples here can be helpful for you: https://gist.github.com/cuixin/10612934 (but I haven't checked it myself).

**Comment by Kamyab96** [comment]
Hey, @alovak  this pkg return error because len of Key is 32 , Thanks again though .
I close the question .
