### ISSUE TITLE
Support for third bitmap

### ISSUE THREAD

**Issue by ferch5003** [moov-io/iso8583#254]
I am getting this error trying to deserialize a message that contains a 130 field:

`error:unmarshalling: deserialize body: failed to unpack field 65: no specification found`

Seeing the Bitmap the bit 65 is turned on, but this bit indicates a third bitmap that is active, not a field, so there is not an specification for this case.

**Comment by alovak** [comment]
@ferch5003 thanks for reporting the issue! I've fixed it here: https://github.com/moov-io/iso8583/pull/255

but I also have to check if it should be fixed for composite fields as well. I hope to fix it for composites today as well.

**Comment by alovak** [comment]
I checked and `Composite` works only with fixed bitmaps - so, the #255 is not relevant here.
