### ISSUE TITLE
Add fuzzing to low level parsers. 

### ISSUE THREAD

**Issue by wadearnold** [moov-io/iso8583#26]
It would be nice to add a fuzzer or two for the low level parsers. Those will need to be rock solid. We've got these in other projects that are ran continiously

https://github.com/moov-io/ach/tree/master/test/fuzz-reader

_Originally posted by @adamdecaf in https://github.com/moov-io/iso8583/issues/20#issuecomment-735941002_

**Comment by mfdeveloper508** [comment]
https://github.com/moov-io/iso8583/pull/28
