### ISSUE TITLE
Use int64 for field.Numeric

### ISSUE THREAD

**Issue by alovak** [moov-io/iso8583#292]
In most of the iso8583 specs, amount fields are 12 digits. Currently, `field.Numerc` is storing value as `int`, which is max `2147483647` (and it's 10 digits). We should use `int64` instead of `int`.

There are some options for fixing this:
1. change type for `field.Numeric` from int to `int64` - a breaking change
2. add new `field.BigNumeric` 😂 which will accept `int64` - looks like an extra complexity

I believe that option 1 is the right one as currently using `int` for amount fields is a bug and should be fixed.  While it's not a backward-compatible change, it fixes the issue and requires a simple upgrade.

P.S. this change should also support `int64` (and `*int64`) in Marshal/Unmarshal in the `field.String` and `field.Numeric`.

**Comment by GalihFajar** [comment]
Hi @alovak kindly assign this one to me, much appreciated!

**Comment by wadearnold** [comment]
What is "Option 3" @alovak? Do you mean option 1? 
Thanks for the help @GalihFajar!

**Comment by alovak** [comment]
@GalihFajar, please join Moov's community Slack here: https://slack.moov.io/ and we can discuss any questions you have in #iso8583 channel as well.

**Comment by alovak** [comment]
closed by @GalihFajar in #294
