### ISSUE TITLE
Question about subfield

### ISSUE THREAD

**Issue by Juniornewxt** [moov-io/iso8583#321]
Friends, how do I use the subfield to assemble the message as in the example?

-----
			48: field.NewString(&field.Spec{
				Length:      999,
				Description: "Info",
				Enc:         encoding.EBCDIC,
				Pref:        prefix.EBCDIC.LLL,
				Tag: &field.TagSpec{
					Sort: sort.StringsByInt,
				},
				Subfields: map[string]field.Field{
					"test1": field.NewString(&field.Spec{
						Length:      2,
						Description: "Transaction Type",
						Enc:         encoding.EBCDIC,
						Pref:        prefix.EBCDIC.Fixed,
					}),
					"test2": field.NewString(&field.Spec{
						Length:      2,
						Description: "From Account",
						Enc:         encoding.EBCDIC,
						Pref:        prefix.EBCDIC.Fixed,
					}),
					"test3": field.NewString(&field.Spec{
						Length:      2,
						Description: "To Account",
						Enc:         encoding.EBCDIC,
						Pref:        prefix.EBCDIC.Fixed,
					}),
				},
			}),

------

message.Field(43, "DM N           CITY  EVANG076")
message.Field(48, How would this look? Here in a way that uses subfields?)

**Comment by alovak** [comment]
You should use data structs to set/get data from composite fields. Here is an example: https://github.com/alovak/cardflow-playground/blob/main/examples/message_test.go

**Comment by Juniornewxt** [comment]
tks my friend
I can't do this without having to create a struct?
I wanted to pass the data inside the assembly I made as in the example, something like?
message.Field(48, test1,"fff",test2,"aaa",test3,"cccc" )
