### ISSUE TITLE
To verify ISO 8583 specification (version 1997, 2000, 2003)

### ISSUE THREAD

**Issue by mfdeveloper508** [moov-io/iso8583#33]
we need to verify the package to support iso 8583 specifications (version 1997, 2000, 2003)
Especially we should verify to parse iso 8583 message using several encoding method

**Comment by vtolstov** [comment]
i'm can add tests after solve my way4 issue. i can add test for tieto and way4 specs . tieto - ascii encoding and way4 bcd encoding

**Comment by alovak** [comment]
@vtolstov it would be great to add tests based on the different specs into the project if there are no issues with legal/license.
