### ISSUE TITLE
Upgrade assert testing framework

### ISSUE THREAD

**Issue by wadearnold** [moov-io/iso8583#4]
Project is currently dependent on `github.com/stretchr/testify/assert` which is a deprecated testing framework. The test's should be updated to use `gopkg.in/check.v1`

**Comment by vxio** [comment]
@adamdecaf I think we can close this issue?

`github.com/stretchr/testify` works well and is being used in our other Moov services.

**Comment by adamdecaf** [comment]
Is `testify` deprecated? Or was that just the v1 series

**Comment by vxio** [comment]
@adamdecaf I don't think so. I couldn't find anything online about `testify` being deprecated.

**Comment by adamdecaf** [comment]
Okay cool. Let's use it then.
