### ISSUE TITLE
Add support for EBCDIC encoding/decoding

### ISSUE THREAD

**Issue by wadearnold** [moov-io/iso8583#5]
The EBCDIC character set is support by ISO858 although typically ASCII is used. 

Support for ECCDIC has been shown in two different implementations. Neither have test cases or are properly structured. 

https://github.com/ideazxy/iso8583/compare/master...mlioo:master

https://github.com/ideazxy/iso8583/compare/master...gpndata:master

Test cases need to be created and readme needs to be updated with support for EBCDIC

**Comment by mfdeveloper508** [comment]
implemented in https://github.com/moov-io/iso8583/pull/20
