### ISSUE TITLE
Implement JSON encoding and decoding of iso8583 message spec

### ISSUE THREAD

**Issue by alovak** [moov-io/iso8583#50]
For [new-version](https://github.com/moov-io/iso8583/tree/new-version) of the iso8583 package, we should be able to encode message specs like this: https://github.com/moov-io/iso8583/blob/new-version/spec87.go#L10
into JSON and decode it from JSON.

**Comment by mfdeveloper508** [comment]
json format of message spec
https://github.com/moov-io/iso8583/pull/53/files#diff-320de18bc12f062e561903156693fd2b891edecb1c07d64d6224e6787aeb32eeR47-R80

xml format of message spec
https://github.com/moov-io/iso8583/pull/53/files#diff-320de18bc12f062e561903156693fd2b891edecb1c07d64d6224e6787aeb32eeR47-R80

**Comment by alovak** [comment]
Let's get back to spec serialization when we know why do we need it...
