### ISSUE TITLE
Implement JSON encoding and decoding of iso8583 message

### ISSUE THREAD

**Issue by alovak** [moov-io/iso8583#51]
For [new-version](https://github.com/moov-io/iso8583/tree/new-version) of the iso8583 package, we should be able to encode message  like this: https://github.com/moov-io/iso8583/blob/new-version/message_test.go#L314
into JSON and decode it from JSON.

Now sure how to implement JSON decoding for messages with typed fields. I'm open to discussing it.

**Comment by mfdeveloper508** [comment]
Sample xml and json files suggested:

<ISO8583>
	<MessageTypeIndicator>0100</MessageTypeIndicator>
	<Bitmap>11110010 00111100 00100100 10000001 00101000 11100000 10011000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 </Bitmap>
	<PrimaryAccountNumber>4276555555555555</PrimaryAccountNumber>
	<ProcessingCode>000000</ProcessingCode>
	<Field4>77700</Field4>
	<Field7>701111844</Field7>
	<Field11>123</Field11>
	<Field12>131844</Field12>
	<Field13>701</Field13>
	<Field14>1902</Field14>
	<Field19>643</Field19>
	<Field22>901</Field22>
	<Field25>2</Field25>
	<Field32>123456</Field32>
	<Field35>4276555555555555=12345678901234567890</Field35>
	<Field37>987654321001</Field37>
	<Field41>00000321</Field41>
	<Field42>120000000000034</Field42>
	<Field43>Test text</Field43>
	<Field49>643</Field49>
	<Field52>\u0001\u0002\u0003\u0004\u0005\u0006\u0007\u0008</Field52>
	<Field53>1234000000000000</Field53>
	<Field120>Another test text</Field120>
</ISO8583>

{
	"bitmap": "11110010 00111100 00100100 10000001 00101000 11100000 10011000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 ",
	"field_11": "123",
	"field_12": "131844",
	"field_120": "Another test text",
	"field_13": "701",
	"field_14": "1902",
	"field_19": "643",
	"field_22": "901",
	"field_25": "2",
	"field_32": "123456",
	"field_35": "4276555555555555=12345678901234567890",
	"field_37": "987654321001",
	"field_4": "77700",
	"field_41": "00000321",
	"field_42": "120000000000034",
	"field_43": "Test text",
	"field_49": "643",
	"field_52": "\u0001\u0002\u0003\u0004\u0005\u0006\u0007\u0008",
	"field_53": "1234000000000000",
	"field_7": "701111844",
	"message_type_indicator": "0100",
	"primary_account_number": "4276555555555555",
	"processing_code": "000000"
}

Field names of json format is snake case string, field names of xml format is camel case string. 
We can indicate field names through Identifier of spec struct (https://github.com/moov-io/iso8583/blob/new-version/field/spec.go#L15)

If there isn't identifier of spec struct, will use description of spec field

**Comment by mfdeveloper508** [comment]
Sample json file:
https://github.com/moov-io/iso8583/blob/new-version/message_test.go#L383-L407

Sample xml file:
https://github.com/moov-io/iso8583/blob/new-version/message_test.go#L449-L473

Field names of json format is snake case string, field names of xml format is camel case string.
We can indicate field names through Identifier of spec struct (https://github.com/moov-io/iso8583/blob/new-version/field/spec.go#L15)

If there isn't identifier of spec struct, will use description of spec field

**Comment by alovak** [comment]
JSON encoding is implemented in #63 

closing this.
