### ISSUE TITLE
Support Hexadecimal encoding of bitmaps

### ISSUE THREAD

**Issue by wadearnold** [moov-io/iso8583#6]
In ISO8583 a bitmap may be represented as 8 bytes of binary data(currently supported) or as 16 hexadecimal characters in the ASCII or EBCDIC character sets. See "Bitmaps" on the [ISO8583 page](https://en.wikipedia.org/wiki/ISO_8583).

A fork currently implements this with test cases. 
https://github.com/ideazxy/iso8583/compare/master...yogyrahmawan:master

**Comment by mfdeveloper508** [comment]
implemented in https://github.com/moov-io/iso8583/pull/20
