### ISSUE TITLE
Upper Hex.

### ISSUE THREAD

**Issue by Juniornewxt** [moov-io/iso8583#60]
My friends, I have a problem because the bitmap is being generated in capital letters.

I need it:

0800A2380001004000080400000000000000000000060223031106022320031106020400890000000000000000000501.00301

But what comes out of my "Go" program is this:

0800a2380001004000080400000000000000000000060223031106022320031106020400890000000000000000000501.00301

notice that the "A" became lowercase "a".

Is there any way to change this?

**Comment by vtolstov** [comment]
mostly character case in hex does not matter, but you can do strings.ToUpper

**Comment by alovak** [comment]
@Juniornewxt I've updated HEX encoding to return capital letters. Please, update the package to v0.3.2 version.

**Comment by alovak** [comment]
btw, to update to the latest version just run this in your terminal (in the package directory):
```
go get github.com/moov-io/iso8583
```

or if you want to install specific version:

```
go get github.com/moov-io/iso8583@v0.3.2
```
