### ISSUE TITLE
What Encoding should I select if I don't want a certain field packed?

### ISSUE THREAD

**Issue by WilliamHuang1995** [moov-io/iso8583#64]
I Want Field 55 to be passed as is when calling Pack() (since it is already in Hex).

What do I assign as encoding?

**Comment by WilliamHuang1995** [comment]
In case I wasn't clear enough
![image](https://user-images.githubusercontent.com/17118667/121772567-9930f980-cba8-11eb-96c1-29d2c463497e.png)
I want to send `82025400` as is when calling message.Pack()

**Comment by vtolstov** [comment]
Binary

сб, 12 июн. 2021 г., 13:09 William Huang ***@***.***>:

**Comment by WilliamHuang1995** [comment]
Thanks it works
