### ISSUE TITLE
Support for EBCDIC character set

### ISSUE THREAD

**Issue by krishishah** [moov-io/iso8583#66]
The official ISO8583-1987 spec references EBCDIC as the character set of choice to encode messages. Certain card schemes also require this.

Could we extend support for this character set? 

How far has ASCII taken users of this lib when integrating with card schemes with regards to message flows?

Am I correct in thinking that it only requires implementation of the ``encoding/Encoder`` and ``prefix/Prefixer`` interfaces to support this?

**Comment by alovak** [comment]
@krishishah you are right. The idea is to add encoder and prefixer using needed encoding.

**Comment by wadearnold** [comment]
Some ideas from a fork. 

Added EBCDIC encoding for Alphanumeric, llvar, and lllvar types https://github.com/mlioo/iso8583/commit/65888ce87ba483c3f2c82a4ea7531c2ae1a5d532

Added missing const for ebcdic
https://github.com/mlioo/iso8583/commit/40c831a2ab1a7eb5fa9b7997507dfc52e44c80a9
