### ISSUE TITLE
Support LLAlphanumeric from/to bytes

### ISSUE THREAD

**Issue by wadearnold** [moov-io/iso8583#7]
Llalphanumeric contains bytes in non-fixed length field, first 2 symbols of the field contains length. 

An implementation exists in a fork but has no test cases. 
https://github.com/ideazxy/iso8583/compare/master...rdingwall:variable_length_alphanumeric_fields

**Comment by mfdeveloper508** [comment]
implemented in https://github.com/moov-io/iso8583/pull/20
