### ISSUE TITLE
input bytes does not match output bytes ? 

### ISSUE THREAD

**Issue by wadearnold** [moov-io/iso8583#78]
I would expect the bytes that I pass into `Unpack` to match the bytes that I get from `Pack` 

```go
func TestBytesMatch(t *testing.T) {
	msg := iso8583.NewMessage(iso8583.Spec87)
	wantMsg := []byte("01007000000000000000164242424242424242123456000000000100")
	err := msg.Unpack(wantMsg)
	if err != nil {
		t.Errorf("failed to pack unpacked message: %v", err)
	}
	rawmsg, err := msg.Pack()
	if err != nil {
		t.Errorf("failed to pack message: %v", err)
	}

	res := bytes.Equal(wantMsg, rawmsg)

	if  !res  {
		t.Errorf("input message does not match output")
	}
}
```

```bash
--- FAIL: TestBytesMatch (0.00s)
    /Users/wadearnold/Documents/GitHub/wadearnold/iso8583/test/issues/issue69_test.go:38: input message does not match output
FAIL
```

Thoughts on why they don't match? If there is always a mutation then is there a way to get the input bytes. This would be useful when `Unpack` and `Pack` fail to know what caused the issue.

**Comment by vtolstov** [comment]
can you provide output of pack to check the difference?

**Comment by alovak** [comment]
@wadearnold I've run your test against master branch and it works for me:

```
go test -v -run TestBytesMatch
=== RUN   TestBytesMatch
--- PASS: TestBytesMatch (0.00s)
PASS
ok      github.com/moov-io/iso8583      0.225s
```

hm...

**Comment by alovak** [comment]
The trick with Unpack is that it will unpack almost anything you give it. Unless it causes decoding errors...

**Comment by alovak** [comment]
@wadearnold, can I close this issue? Were you able to find the issue?

I tested your example locally, and it worked.

**Comment by alovak** [comment]
Closing this as there is no confirmation of the issue.
