### ISSUE TITLE
fields vs fieldsMap 

### ISSUE THREAD

**Issue by wadearnold** [moov-io/iso8583#79]
In Message when do you use fields vs fieldsMap? Can someone document this in message.go? Although these struck fields are not exported it would be nice if they had comments. 

```go
type Message struct {
	fields    map[int]field.Field
	spec      *MessageSpec
	data      interface{}
	fieldsMap map[int]struct{}
	bitmap    *field.Bitmap
}
```

**Comment by alovak** [comment]
`fieldsMap` tracks which fields were set
`fields` stores all fields according to the spec

**Comment by wadearnold** [comment]
Can you add comments into the source code struct and we can close this issue.

**Comment by alovak** [comment]
Done!

https://github.com/moov-io/iso8583/blob/master/message.go#L18
